"""
Django settings for spk_maza project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

if os.environ.get('RAILWAY_ENVIRONMENT'):
    DEBUG = True 

if os.environ.get('RAILWAY_ENVIRONMENT') and os.environ.get('DJANGO_SUPERUSER_USERNAME'):
    from django.core.management import execute_from_command_line
    execute_from_command_line(['manage.py', 'createsuperuser', '--noinput'])

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ========== SECURITY SETTINGS ==========
SECRET_KEY = 'django-insecure-auxuh+8=9(%yb&6hpsszc-y)v2x1t9=k1zrnsm33zt!xz96y(9'

# DEBUG: True untuk development, False untuk production
DEBUG = True # ← SET FALSE untuk Railway

# Host yang diizinkan mengakses
ALLOWED_HOSTS = [
    'kuemaza-production.up.railway.app',
    # 'kuemaza-production.railway.app',
    'localhost',
    '127.0.0.1',
    '.railway.app',
]

# CSRF & Security untuk Railway (HTTPS)
CSRF_TRUSTED_ORIGINS = [
    'https://kuemaza-production.up.railway.app',
    'https://*.railway.app',
    'https://*.up.railway.app',
]

# HTTPS settings untuk Railway
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_DOMAIN = 'kuemaza-production.up.railway.app'
CSRF_USE_SESSIONS = True
SESSION_COOKIE_DOMAIN = 'kuemaza-production.up.railway.app'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 minggu

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = True

CORS_ALLOWED_ORIGINS = [
    'https://kuemaza-production.up.railway.app',
]

# ========== APPLICATION DEFINITION ==========
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spk',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'spk.middleware.NoCacheMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware', 
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
]

WSGI_APPLICATION = 'spk_maza.wsgi.application'
ROOT_URLCONF = 'spk_maza.urls'

# Cache Control Settings
CACHE_MIDDLEWARE_SECONDS = 0  # No cache
CACHE_MIDDLEWARE_KEY_PREFIX = 'spk'
CACHE_MIDDLEWARE_ALIAS = 'default'

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ← Optional
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spk_maza.wsgi.application'

# ========== DATABASE ==========
if os.environ.get('DATABASE_URL'):  # Railway kasih ini otomatis
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
    }
else:
    # Fallback ke SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'db.sqlite3',
        }
    }

# ========== PASSWORD VALIDATION ==========
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ========== INTERNATIONALIZATION ==========
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ========== STATIC FILES (CSS, JS, Images) ==========
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ========== DEFAULT SETTINGS ==========
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEBUG = False

# ========== CUSTOM SETTINGS ==========
LOGIN_URL = '/spk/login/'
LOGIN_REDIRECT_URL = '/spk/home/'
LOGOUT_REDIRECT_URL = '/spk/login/'
